name: Unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make test cases
      run: make run 3_Implementation/test
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
